//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pittools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionImage
    {
        public int ID { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string ImageExt { get; set; }
    
        public virtual Collection Collection { get; set; }
    }
}
